name: Lint Check

on:
  push:
    branches:
      - main
# This is what will cancel the workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Continuous integration
        uses: ./.github/actions

      - name: Test Coverage
        working-directory: ./backend-project
        run: npm run test:cov

      - name: Test Cat Coverage
        run: cat ${{ github.workspace }}/backend-project/coverage/coverage-final.json

      - name: Verify Code Coverage
        id: verify-coverage
        uses: namnh240795/verify-coverage-action@v1.0.4
        with:
            threshhold: 90
            jsonSummary: ${{ github.workspace }}/backend-project/coverage/coverage-final.json
     
      - name: Notify failed
        if: steps.verify-coverage.outputs.pass != 'true'
        run: echo "Coverage is less than 90%"
      
      - name: if coverage is more than 90%
        if: steps.verify-coverage.outputs.pass == 'true'
        run: exit 1
