name: Lint Check

on:
  push:
    branches:
      - main
# This is what will cancel the workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Continuous integration
        uses: ./.github/actions

      - name: Test Coverage
        working-directory: ./backend-project
        run: npm run test:cov

      - name: Save Coverage To Outputs
        id: coverage
        working-directory: ./backend-project
        run: 
            echo $GITHUB_WORKSPACE
            echo $GITHUB_WORKSPACE/jsonSummary.json
            echo "jsonSummaryFile=$GITHUB_WORKSPACE/jsonSummary.json" >> $GITHUB_ENV

      - name: Verify Code Coverage
        uses: namnh240795/verify-coverage-action@v1.0.1
        with:
            threshhold: 90
            jsonSummary: ${{ steps.coverage.outputs.jsonSummary }}
